class Employee {
    constructor() {

    }

    EmployeeDefault = {
        AllowAccessByTime: false,
        BirthPlace: "",
        BirthOfDate: "",
        CreatedBy: "lmhoa",
        CreatedDate: "2019-06-13T10:07:13.973973Z",
        CurrentAddress: "",
        CurrentCountry: "",
        CurrentDistrict: "",
        CurrentPostalCode: "",
        CurrentProvince: "",
        CurrentVillage: "",
        EditMode: 0,
        EditVersion: "AAAAAAAGiVc=",
        Email: "toanloc.h3t@gmail.com",
        EmergencyContactAddress: "",
        EmergencyContactEmail: "",
        EmergencyContactMobile: "",
        EmergencyContactName: "",
        EmergencyContactRelation: "",
        EmergencyContactTel: "",
        EmergencyPostalCode: "",
        EmployeeCode: "admin",
        EmployeeID: "fd5fe3e2-536d-4e67-bb50-85ed1ab4d765",
        EmployeeType: 0,
        FileType: 3,
        FirstName: "",
        FullName: "ADMIN",
        Gender: 0,
        GenderName: "Nam",
        HomeLand: "",
        HomeTel: "",
        IdentifyNumber: "",
        IdentifyNumberIssuedPlace: "",
        IsAllowUseSoftware: true,
        IsApproved: false,
        IsChangePinCode: false,
        IsConfirmMISAID: 1,
        IsGenerate: false,
        IsRestaurantChainNotChainOrNotMaster: false,
        LastName: "",
        ListRoleID: "9",
        MaritalStatus: "",
        Mobile: "0359346580",
        ModifiedBy: "lmhoa",
        ModifiedDate: "2021-08-13T07:34:19.28028Z",
        Nationality: "",
        NativeAddress: "",
        NativeCountry: "Việt Nam",
        NativeDistrict: "",
        NativePostalCode: "",
        NativeProvince: "",
        NativeVillage: "",
        NumberCloseConfirmMISAID: 0,
        PassportIssuedPlace: "",
        PassportNumber: "",
        PinCode: "",
        ReasonTermination: "",
        Religion: "",
        Salary: 0,
        StatusID: 1,
        StatusName: "Chính thức",
        StatusName_de: "Offiziell",
        StatusName_en: "Official",
        checkpassword: false,
    }

}

export default new Employee()